INSERT INTO FittingType values (10,'UA', 2,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (13,'UAC', 2,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (16,'UAZ', 2,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (20,'UX', 2,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (21,'UXL', 2,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (40,'UL', 2,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (30,'UD', 2,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (110,'URA', 2,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (113,'URAC', 2,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (116,'URAZ', 2,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (120,'URX', 2,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (121,'URXL', 2,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (140,'URL', 2,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (130,'URD', 2,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (1510,'PCA', 2,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (1513,'PCAC', 2,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (1516,'PCAZ', 2,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (1520,'PCX', 2,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (1521,'PCXL', 2,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (1540,'PCL', 2,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (1530,'PCD', 2,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (1010,'BOA', 1,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (1013,'BOAC', 1,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (1016,'BOAZ', 1,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (1020,'BOX', 1,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (1021,'BOXL', 1,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (1040,'BOL', 1,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (1030,'BOD', 1,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (210,'UMA', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (213,'UMAC', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (216,'UMAZ', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (220,'UMX', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (221,'UMXL', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (240,'UML', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (230,'UMD', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (310,'UMCA', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (313,'UMCAC', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (316,'UMCAZ', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (320,'UMCX', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (321,'UMCXL', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (340,'UMCL', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (330,'UMCD', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (2010,'UMNA', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (2013,'UMNAC', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (2016,'UMNAZ', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (2020,'UMNX', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (2021,'UMNXL', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (2040,'UMNL', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (2030,'UMND', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (8310,'UMIA', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (8313,'UMIAC', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (8316,'UMIAZ', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (8320,'UMIX', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (8321,'UMIXL', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (8340,'UMIL', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (8330,'UMID', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (8210,'UMCIA', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (8213,'UMCIAC', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (8216,'UMCIAZ', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (8220,'UMCIX', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (8221,'UMCIXL', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (8240,'UMCIL', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (8230,'UMCID', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (7910,'UMNIA', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (7913,'UMNIAC', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (7916,'UMNIAZ', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (7920,'UMNIX', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (7921,'UMNIXL', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (7940,'UMNIL', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (7930,'UMNID', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (410,'UFA', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (413,'UFAC', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (416,'UFAZ', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (420,'UFX', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (421,'UFXL', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (440,'UFL', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (430,'UFD', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (2110,'UFNA', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (2113,'UFNAC', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (2116,'UFNAZ', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (2120,'UFNX', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (2121,'UFNXL', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (2140,'UFNL', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (2130,'UFND', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (610,'AMA', 0,'${TY} ${TU} ${TH} ${OR}');
INSERT INTO FittingType values (613,'AMAC', 0,'${TY} ${TU} ${TH} ${OR}');
INSERT INTO FittingType values (616,'AMAZ', 0,'${TY} ${TU} ${TH} ${OR}');
INSERT INTO FittingType values (620,'AMX', 0,'${TY} ${TU} ${TH} ${OR}');
INSERT INTO FittingType values (621,'AMXL', 0,'${TY} ${TU} ${TH} ${OR}');
INSERT INTO FittingType values (640,'AML', 0,'${TY} ${TU} ${TH} ${OR}');
INSERT INTO FittingType values (630,'AMD', 0,'${TY} ${TU} ${TH} ${OR}');
INSERT INTO FittingType values (710,'AMCA', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (713,'AMCAC', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (716,'AMCAZ', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (720,'AMCX', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (721,'AMCXL', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (740,'AMCL', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (730,'AMCD', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (2410,'AMNA', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (2413,'AMNAC', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (2416,'AMNAZ', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (2420,'AMNX', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (2421,'AMNXL', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (2440,'AMNL', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (2430,'AMND', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (810,'AFA', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (813,'AFAC', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (816,'AFAZ', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (820,'AFX', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (821,'AFXL', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (840,'AFL', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (830,'AFD', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (2310,'AFNA', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (2313,'AFNAC', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (2316,'AFNAZ', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (2320,'AFNX', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (2321,'AFNXL', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (2340,'AFNL', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (2330,'AFND', 0,'${TY} ${TU} ${TH}');
INSERT INTO FittingType values (510,'AURA', 1,'${TY} ${AD} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (513,'AURAC', 1,'${TY} ${AD} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (516,'AURAZ', 1,'${TY} ${AD} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (520,'AURX', 1,'${TY} ${AD} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (521,'AURXL', 1,'${TY} ${AD} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (540,'AURL', 1,'${TY} ${AD} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (530,'AURD', 1,'${TY} ${AD} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (5010,'EA', 2,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (5013,'EAC', 2,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (5016,'EAZ', 2,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (5020,'EX', 2,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (5021,'EXL', 2,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (5040,'EL', 2,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (5030,'ED', 2,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (3010,'TA', 3,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (3013,'TAC', 3,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (3016,'TAZ', 3,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (3020,'TX', 3,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (3021,'TXL', 3,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (3040,'TL', 3,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (3030,'TD', 3,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (4010,'CA', 4,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (4013,'CAC', 4,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (4016,'CAZ', 4,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (4020,'CX', 4,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (4021,'CXL', 4,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (4040,'CL', 4,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (4030,'CD', 4,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (3510,'YA', 3,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (3513,'YAC', 3,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (3516,'YAZ', 3,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (3520,'YX', 3,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (3521,'YXL', 3,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (3540,'YL', 3,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (3530,'YD', 3,'${TY} ${TU} ${OR} ${GR}');
INSERT INTO FittingType values (5210,'EMA', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (5213,'EMAC', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (5216,'EMAZ', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (5220,'EMX', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (5221,'EMXL', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (5240,'EML', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (5230,'EMD', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (5310,'EMCA', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (5313,'EMCAC', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (5316,'EMCAZ', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (5320,'EMCX', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (5321,'EMCXL', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (5340,'EMCL', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (5330,'EMCD', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (5810,'EMNA', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (5813,'EMNAC', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (5816,'EMNAZ', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (5820,'EMNX', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (5821,'EMNXL', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (5840,'EMNL', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (5830,'EMND', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (6110,'ORA', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (6113,'ORAC', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (6116,'ORAZ', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (6120,'ORX', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (6121,'ORXL', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (6140,'ORL', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (6130,'ORD', 1,'${TY} ${TU} ${TH} ${OR} ${GR}');
INSERT INTO FittingType values (1310,'OBA', 0,'${TY} ${TU}');
INSERT INTO FittingType values (1313,'OBAC', 0,'${TY} ${TU}');
INSERT INTO FittingType values (1316,'OBAZ', 0,'${TY} ${TU}');
INSERT INTO FittingType values (1320,'OBX', 0,'${TY} ${TU}');
INSERT INTO FittingType values (1321,'OBXL', 0,'${TY} ${TU}');
INSERT INTO FittingType values (1340,'OBL', 0,'${TY} ${TU}');
INSERT INTO FittingType values (1330,'OBD', 0,'${TY} ${TU}');

INSERT INTO Oring values (1, 'JN');
INSERT INTO Oring values (2, 'JV');
INSERT INTO Oring values (3, 'JS');
INSERT INTO Oring values (4, 'JE');
INSERT INTO Oring values (6, 'JH');

INSERT INTO Grip values (10, 'JAB', 1);
INSERT INTO Grip values (20, 'BAB', 1);
INSERT INTO Grip values (24, 'BX', 1);
INSERT INTO Grip values (34, 'BSX', 1);
INSERT INTO Grip values (25, 'BXL', 1);
INSERT INTO Grip values (27, 'BL', 1);
INSERT INTO Grip values (21, 'BD', 1);
INSERT INTO Grip values (12, 'JAB', 1);
INSERT INTO Grip values (22, 'BAB', 1);

INSERT INTO TubeDim values (6, '6 mm');
INSERT INTO TubeDim values (8, '8 mm');
INSERT INTO TubeDim values (10, '10 mm');
INSERT INTO TubeDim values (12, '12 mm');
INSERT INTO TubeDim values (14, '14 mm');
INSERT INTO TubeDim values (15, '15 mm');
INSERT INTO TubeDim values (16, '16 mm');
INSERT INTO TubeDim values (18, '18 mm');
INSERT INTO TubeDim values (20, '20 mm');
INSERT INTO TubeDim values (22, '22 mm');
INSERT INTO TubeDim values (25, '25 mm');
INSERT INTO TubeDim values (28, '28 mm');
INSERT INTO TubeDim values (30, '30 mm');
INSERT INTO TubeDim values (35, '35 mm');
INSERT INTO TubeDim values (38, '38 mm');
INSERT INTO TubeDim values (40, '40 mm');
INSERT INTO TubeDim values (44, '44.5 mm');
INSERT INTO TubeDim values (71, '1/8');
INSERT INTO TubeDim values (72, '1/4');
INSERT INTO TubeDim values (73, '3/8');
INSERT INTO TubeDim values (74, '1/2');
INSERT INTO TubeDim values (75, '3/4');
INSERT INTO TubeDim values (76, '1"');
INSERT INTO TubeDim values (77, '1"1/4');
INSERT INTO TubeDim values (78, '1"1/2');
INSERT INTO TubeDim values (79, '2"');

INSERT INTO Adaptor values (6, '6 mm');
INSERT INTO Adaptor values (8, '8 mm');
INSERT INTO Adaptor values (10, '10 mm');
INSERT INTO Adaptor values (12, '12 mm');
INSERT INTO Adaptor values (14, '14 mm');
INSERT INTO Adaptor values (15, '15 mm');
INSERT INTO Adaptor values (16, '16 mm');
INSERT INTO Adaptor values (18, '18 mm');
INSERT INTO Adaptor values (20, '20 mm');
INSERT INTO Adaptor values (22, '22 mm');
INSERT INTO Adaptor values (25, '25 mm');
INSERT INTO Adaptor values (28, '28 mm');
INSERT INTO Adaptor values (30, '30 mm');
INSERT INTO Adaptor values (35, '35 mm');
INSERT INTO Adaptor values (38, '38 mm');
INSERT INTO Adaptor values (40, '40 mm');
INSERT INTO Adaptor values (44, '44.5 mm');
INSERT INTO Adaptor values (71, '1/8');
INSERT INTO Adaptor values (72, '1/4');
INSERT INTO Adaptor values (73, '3/8');
INSERT INTO Adaptor values (74, '1/2');
INSERT INTO Adaptor values (75, '3/4');
INSERT INTO Adaptor values (76, '1"');
INSERT INTO Adaptor values (77, '1"1/4');
INSERT INTO Adaptor values (78, '1"1/2');
INSERT INTO Adaptor values (79, '2"');

INSERT INTO ThreadDim values (10, 'M10x100');
INSERT INTO ThreadDim values (12, 'M12x100');
INSERT INTO ThreadDim values (14, 'M14x150');
INSERT INTO ThreadDim values (16, 'M16x150');
INSERT INTO ThreadDim values (18, 'M18x150');
INSERT INTO ThreadDim values (20, 'M20x150');
INSERT INTO ThreadDim values (22, 'M22x150');
INSERT INTO ThreadDim values (24, 'M24x150');
INSERT INTO ThreadDim values (27, 'M27x150');
INSERT INTO ThreadDim values (30, 'M30x150');
INSERT INTO ThreadDim values (33, 'M33x200');
INSERT INTO ThreadDim values (39, 'M39x200');
INSERT INTO ThreadDim values (42, 'M42x200');
INSERT INTO ThreadDim values (45, 'M45x200');
INSERT INTO ThreadDim values (48, 'M48x200');
INSERT INTO ThreadDim values (60, 'M60x200');
INSERT INTO ThreadDim values (71, 'G1/8');
INSERT INTO ThreadDim values (72, 'G1/4');
INSERT INTO ThreadDim values (73, 'G3/8');
INSERT INTO ThreadDim values (74, 'G1/2');
INSERT INTO ThreadDim values (75, 'G3/4');
INSERT INTO ThreadDim values (76, 'G1"');
INSERT INTO ThreadDim values (77, 'G1"1/4');
INSERT INTO ThreadDim values (78, 'G1"1/2');
INSERT INTO ThreadDim values (79, 'G2"');

INSERT INTO Supplier (supplierName, supplierAddress, supplierContactNum, supplierNIP, discount) values ('F.B.O.', 'ZI de Boisse BP78 - FR87200 SAINT JUNIEN', '+33 555 02 80 77 - Jean-Paul HELIAS', '1234567890', 0.8);

commit;